// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jipprjgyxnahxjnzrixo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppcHByamd5eG5haHhqbnpyaXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDU1MzAsImV4cCI6MjA2NTU4MTUzMH0.mkJ9BMtjzEPWD60kVeiUh3Q3yZ6NSmprAV6Jnj9a8sU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);